Repository GDG-on-Campus-KNU/GDG-KNU-Hackathon-FE, pull requests merged in 2024-10, with the labels that each got.

#12 [FEATURE] 해커톤 지원 섹션 구현
  packages/client/.gitignore
  packages/client/src/assets/images/cloud-common1.svg
  packages/client/src/assets/images/cloud-common2.svg
  packages/client/src/assets/images/cloud-common3.svg
  packages/client/src/assets/images/envelop-behind.svg
  packages/client/src/assets/images/logoBlue.svg
  packages/client/src/components/ApplyPosition/Container.style.ts
  packages/client/src/components/ApplyPosition/Container.tsx
  packages/client/src/components/ApplyPosition/Item.style.ts
  packages/client/src/components/ApplyPosition/Item.tsx
  packages/client/src/components/Button/ApproveButton.style.ts
  packages/client/src/components/Button/ApproveButton.tsx
  packages/client/src/components/Button/SubmitButton.style.ts
  packages/client/src/components/Button/SubmitButton.tsx
  packages/client/src/components/Form/Input.style.ts
  packages/client/src/components/Form/Input.tsx
  packages/client/src/components/Modal/ApplyModal.style.ts
  packages/client/src/components/Modal/ApplyModal.tsx
  packages/client/src/configurations/.gitkeep
  packages/client/src/context/ApplyPositionContext.tsx
  packages/client/src/context/ModalContext.tsx
  packages/client/src/context/useApplyModal.tsx
  packages/client/src/context/useApplyPosition.tsx
  packages/client/src/hooks/.gitkeep
  packages/client/src/hooks/useApply.tsx
  packages/client/src/hooks/useApplySectionAnimation.tsx
  packages/client/src/main.tsx
  packages/client/src/pages/ApplySection/ApplySection.style.ts
  packages/client/src/pages/ApplySection/ApplySection.tsx
  packages/client/src/pages/HeroSection/HeroSection.tsx
  packages/client/src/pages/Page.tsx
  packages/client/src/pages/TimeLineSection/TimeLineSection.tsx
  packages/client/src/services/.gitkeep
  packages/client/src/services/index.d.ts
  packages/client/src/services/service.ts
  packages/client/src/styles/global.ts
Labels: ✨ Feature, 📡 API

#11 [FEATURE] Admin Page 프로젝트 세팅
  packages/admin/.eslintignore
  packages/admin/eslint.config.js
  packages/admin/package.json
  packages/admin/postcss.config.js
  packages/admin/src/App.css
  packages/admin/src/App.tsx
  packages/admin/src/api/instance/index.tsx
  packages/admin/src/components/common/button/index.tsx
  packages/admin/src/index.css
  packages/admin/src/main.tsx
  packages/admin/src/pages/QR-scan/index.tsx
  packages/admin/src/pages/chat/index.tsx
  packages/admin/src/pages/home/index.tsx
  packages/admin/src/pages/people-management/index.tsx
  packages/admin/src/routes/components/.keep
  packages/admin/src/routes/index.tsx
  packages/admin/src/routes/path.ts
  packages/admin/src/store/.keep
  packages/admin/src/styles/index.tsx
  packages/admin/src/styles/reset.css
  packages/admin/src/theme/.keep
  packages/admin/tailwind.config.js
  packages/admin/tsconfig.app.json
  packages/admin/tsconfig.json
  packages/admin/tsconfig.node.json
  packages/admin/vite.config.ts
Labels: 📦 Environment

#25 refactor: 폴더 구조 수정
  packages/admin/components.json
  packages/admin/package.json
  packages/admin/src/App.tsx
  packages/admin/src/app/lib/utils.ts
  packages/admin/src/app/routes/index.tsx
  packages/admin/src/app/routes/path.ts
  packages/admin/src/components/ui/avatar.tsx
  packages/admin/src/components/ui/button.tsx
  packages/admin/src/components/ui/input.tsx
  packages/admin/src/components/ui/scroll-area.tsx
  packages/admin/src/components/ui/table.tsx
  packages/admin/src/main.tsx
  packages/admin/src/pages/QR-code-scanner/index.tsx
  packages/admin/src/pages/chat/data/CHAT.json
  packages/admin/src/pages/chat/index.tsx
  packages/admin/src/pages/main/index.tsx
  packages/admin/src/pages/people-management/data/PERSON.json
  packages/admin/src/pages/people-management/index.tsx
  packages/admin/src/shared/api/instance/index.tsx
  packages/admin/src/shared/assets/react.svg
  packages/admin/src/shared/components/common/.keep
  packages/admin/src/shared/components/feature/.keep
  packages/admin/src/shared/components/ui/avatar.tsx
  packages/admin/src/shared/components/ui/button.tsx
  packages/admin/src/shared/components/ui/input.tsx
  packages/admin/src/shared/components/ui/scroll-area.tsx
  packages/admin/src/shared/components/ui/table.tsx
  packages/admin/src/shared/store/.keep
  packages/admin/src/shared/styles/index.ts
  packages/admin/src/shared/styles/reset.css
  packages/client/tsconfig.node.json
  tsconfig.json
Labels: 📦 Environment, ♻️ Refactoring

#27 전체 코드 변경 및 컴포넌트 분리
  packages/admin/eslint.config.js
  packages/admin/package.json
  packages/admin/src/app/routes/index.tsx
  packages/admin/src/app/routes/path.ts
  packages/admin/src/feature/QR-code-scanner/declaration.d.ts
  packages/admin/src/feature/QR-code-scanner/index.ts
  packages/admin/src/feature/QR-code-scanner/ui/index.tsx
  packages/admin/src/feature/people-management/api/hook/getPeopleData.ts
  packages/admin/src/feature/people-management/api/mock/useGetPeople.ts
  packages/admin/src/feature/people-management/components/common/MainContents.tsx
  packages/admin/src/feature/people-management/components/feature/InputField.tsx
  packages/admin/src/feature/people-management/components/feature/PeopleTable.tsx
  packages/admin/src/feature/people-management/data/PEOPLE.json
  packages/admin/src/feature/people-management/hook/useDeletePerson.ts
  packages/admin/src/feature/people-management/hook/useFilteredPeople.ts
  packages/admin/src/feature/people-management/hook/useUpdatePersonStatus.ts
  packages/admin/src/feature/people-management/index.ts
  packages/admin/src/feature/people-management/ui/index.tsx
  packages/admin/src/pages/chat/data/CHAT.json
  packages/admin/src/pages/chat/index.tsx
  packages/admin/src/pages/main/index.tsx
  packages/admin/src/pages/people-management/data/PERSON.json
  packages/admin/src/pages/people-management/index.tsx
  packages/admin/src/shared/components/feature/layout/header.tsx
  packages/admin/src/shared/components/feature/layout/sidebar.tsx
  tsconfig.json
  yarn.lock
Labels: ✨ Feature, ♻️ Refactoring

#29 검색엔진최적화 및 API 연동
  packages/client/index.html
  packages/client/package.json
  packages/client/public/favicon.png
  packages/client/public/preview.png
  packages/client/public/vite.svg
  packages/client/src/components/Button/ApproveButton.style.ts
  packages/client/src/components/Button/SubmitButton.style.ts
  packages/client/src/components/Spinner/Spinner.styles.ts
  packages/client/src/components/Spinner/Spinner.tsx
  packages/client/src/components/Text/Text.tsx
  packages/client/src/hooks/useApply.tsx
  packages/client/src/main.tsx
  packages/client/src/pages/ApplySection/ApplySection.tsx
  packages/client/src/services/service.ts
  yarn.lock
Labels: 🚀 Deploy, ✨ Feature

#33 배포 테스트
  .github/workflows/deploy-admin.yml
  .gitignore
  packages/.DS_Store
  packages/admin/.eslintignore
  packages/admin/.prettierignore
  packages/admin/index.html
  packages/admin/public/favicon.png
  packages/admin/public/vite.svg
Labels: 🚀 Deploy

#41 첫 페이지 수정
  .github/workflows/deploy-admin.yml
  packages/admin/components.json
  packages/admin/package.json
  packages/admin/src/features/QR-code-scanner/declaration.d.ts
  packages/admin/src/features/QR-code-scanner/index.ts
  packages/admin/src/features/QR-code-scanner/ui/QRCodeScannerPage.tsx
  packages/admin/src/features/QR-code-scanner/ui/index.ts
  packages/admin/src/features/index.ts
  packages/admin/src/features/people-management/api/hook/getPeopleData.ts
  packages/admin/src/features/people-management/api/hook/index.ts
  packages/admin/src/features/people-management/api/index.ts
  packages/admin/src/features/people-management/api/mock/index.ts
  packages/admin/src/features/people-management/api/mock/useGetPeople.ts
  packages/admin/src/features/people-management/components/common/MainContents.tsx
  packages/admin/src/features/people-management/components/common/index.ts
  packages/admin/src/features/people-management/components/feature/InputField.tsx
  packages/admin/src/features/people-management/components/feature/PeopleTable.tsx
  packages/admin/src/features/people-management/components/feature/index.ts
  packages/admin/src/features/people-management/components/index.ts
  packages/admin/src/features/people-management/data/PEOPLE.json
  packages/admin/src/features/people-management/hook/index.ts
  packages/admin/src/features/people-management/hook/useDeletePerson.ts
  packages/admin/src/features/people-management/hook/useFilteredPeople.ts
  packages/admin/src/features/people-management/hook/useUpdatePersonStatus.ts
  packages/admin/src/features/people-management/index.ts
  packages/admin/src/features/people-management/ui/PeopleManagementPage.tsx
  packages/admin/src/features/people-management/ui/index.ts
  packages/admin/src/shared/hooks/.keep
Labels: 🚀 Deploy, ♻️ Refactoring
